### ISSUE TITLE
Email form doesn’t work

### ISSUE THREAD

**Issue by mistermantas** [choraleapp/chorale#21]
Check `content/contact.html` to see what’s wrong with the form. It should be at the bottom of the HTML page.

Button doesn’t work.

**IMPORTANT UPDATE:** We use Netlify: https://www.netlify.com/docs/form-handling/

The form shouldn’t expose any email. This issue is still open, so it means you can still take this one on! :)

**Comment by rcass** [comment]
I can take a look 👍

**Comment by jrwarwick** [comment]
At a glance:  https://www.netlify.com/docs/form-handling/  seems to indicate that you need to add:   data-netlify="true" 
to the <form> tag on line 78.

**Comment by mistermantas** [comment]
That's probably it, 'cause I just quickly added in the form.

**Comment by mistermantas** [comment]
Removing form.
