### ISSUE TITLE
On mobile Safari, the menu does not work

### ISSUE THREAD

**Issue by mistermantas** [choraleapp/chorale#6]
Wow.

**Comment by mistermantas** [comment]
I don’t have Safari or an iPhone so someone else will have to fix this!

Don’t forget to join our [Discord](https://discord.io/choraleapp) if you have Qs, this bug is stilll oopen.

**Comment by Jayflux** [comment]
@mistermantas can pick this up, could you define does not work? Whats the problem exactly

**Comment by mistermantas** [comment]
@Jayflux Please do! 🙂

**Comment by mistermantas** [comment]
Fixed with #7.
