### ISSUE TITLE
On mobile, currency switching doesn't work

### ISSUE THREAD

**Issue by mistermantas** [choraleapp/chorale#9]
Tested on Android Chrome Canary.

Preview: https://www.choraleapp.com/pricing

Uses micromodal and some JavaScript at the bottom.

Could someone take this?

**Comment by agathver** [comment]
I'm interested to give it a try!

**Comment by agathver** [comment]
@mistermantas The issue lies in the fact that a gesture for scrolling is being interpreted as a tap on the currency. Instead of bare links, it may be sensible to use a `<select>` element

**Comment by siwalikm** [comment]
@mistermantas fixed this issue. Please check PR => https://github.com/choraleapp/chorale/pull/10

**Comment by mistermantas** [comment]
@agathver Couldn’t use `<select>` for such a thing, but since @siwalikm already made a PR, I can close the issue anyway.
